prueba/prueba/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from wagtail.admin import urls as wagtailadmin_urls
from wagtail.core import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('usuarios.urls')),
    path('cms/', include(wagtailadmin_urls)),
    path('documents/', include(wagtaildocs_urls)),
    path('pages/', include(wagtail_urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

prueba/usuarios/urls.py
from django.urls import path
from usuarios import views as v

app_name = "aplication"
urlpatterns = [
    path('', v.inicio, name = "inicio"),
    path ( "detalle_<int:id>/", v.detalle, name = "detalle"),
    path ('create/', v.create_user, name = "create"),
    path ('editar_<int:id>/', v.update_user, name = "update"),
    path ('delete_<int:id>/', v.delete, name = "delete")
]

prueba/blog/models.py
from django.db import models

# Create your models here.

prueba/usuarios/models.py
from django.db import models

# Create your models here.
class Usuarios (models.Model):
    
    nombre = models.CharField(max_length=100, blank=False, null=False)
    genero = models.CharField(max_length=100, blank=False, null=False)

    def __str__(self):
        return self.nombre

prueba/usuarios/forms.py
from django.forms import ModelForm
from .models import Usuarios
class UsuarioForm(ModelForm):
    class Meta:
        model = Usuarios
        fields = '__all__'
    

prueba/blog/views.py
from django.shortcuts import render

# Create your views here.

prueba/usuarios/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Usuarios
from .forms import UsuarioForm

def inicio (request):
    usuarios = Usuarios.objects.all()
    context = {
        "usuarios":usuarios
    }
    return render(request, "usuarios/inicio.html", context)

def detalle(request, id):
    detail_user = get_object_or_404(Usuarios, pk = id)
    context = {
        'detail_user':detail_user
    }
    return render(request, "usuarios/detail.html", context)

def create_user (request) :
    if request.method == "POST" :
        usuario_form = UsuarioForm(request.POST)
        if usuario_form.is_valid() :
            usuario_form.save()
            return redirect('aplication:inicio')
    else:
            usuario_form = UsuarioForm()
    return render (request, "usuarios/create.html", {"usuario_form": usuario_form} )


def update_user(request, id):
    user = get_object_or_404(Usuarios, id = id)
    if request.method =="POST" :
        user_form = UsuarioForm(request.POST, instance=user)
        if user_form.is_valid():
            user_form.save()
            return redirect('aplication:inicio')
    else:
            user_form = UsuarioForm(instance=user)
    return render (
            request, "usuarios/editar.html",
            {
                'user_form': user_form
            }
        )

def delete(request , id) :
    user = get_object_or_404(Usuarios , pk = id)

    if user :
        user.delete()

    return redirect('aplication:inicio')

prueba/templates/usuarios/create.html
{% load static %}


<link rel="stylesheet" href="{% static '/bootstrap.min.css' %}">

<div>
<form method="POST">
            {% csrf_token %}
            {{ usuario_form.as_p }}

            <button class="btn btn-success">Crear</button>
</form>
</div>

prueba/templates/usuarios/detail.html
{% load static %}


<link rel="stylesheet" href="{% static '/bootstrap.min.css' %}">

<div class="container mt-5">



        <p>Nombre : {{ detail_user.nombre }}</p>
        <p> Genero : {{ detail_user.genero}}</p>
       
   

        

    </div>

prueba/templates/usuarios/editar.html
 <div class="container mb-5">

        <form method="POST">
            {% csrf_token %}
            {{ user_form.as_p }}

            <button class="btn btn-success">Guardar</button>
        </form>

    </div>

prueba/templates/usuarios/inicio.html
{% load static %}


<link rel="stylesheet" href="{% static '/bootstrap.min.css' %}">

<div>
  <a href={% url 'aplication:create' %} class="btn btn-outline-dark mt-5">Crear nuevo usuario </a>


<table class="table table-bordered table-info mt-5 text-center">
        <thead>
            <tr>
            <th>Id</th>
            <th>Nombre</th>
            <th> Genero </th>
            
            <th>Opciones</th>
            </tr>
        </thead>
        <tbody>
            {% for user in usuarios %}
                <tr>
                    <th>{{ user.id }}</th>
                    <td>{{ user.nombre }}</td>
                    <td>{{ user.genero }}</td>
            
                    <td>
                         <a href="detalle_{{ user.id }}" class="btn btn-sucess">Ver mas</a>
                        <a href= "editar_{{ user.id }}" class="btn btn-primary">Editar</a>
                        <a href="delete_{{ user.id }}" class="btn btn-danger">Eliminar</a> 
                    </td>
                </tr>
            {% endfor %}
        </tbody>
        </table>



</div>